### ISSUE TITLE
Setting NODE_ENV cross platform....

### ISSUE THREAD

**Issue by mikekidder** [gaearon/library-boilerplate#2]
I was going to recommend Envify to set Environment variables in the npm scripts, but found a solution:

https://github.com/remy/nodemon/issues/184#issuecomment-87378478

Works in Windows!

![npm_env_windows](https://cloud.githubusercontent.com/assets/41694/8712889/762bcb68-2b27-11e5-987c-054436f08475.png)

**Comment by gaearon** [comment]
It doesn't work for OS X though, does it? I get `undefined` in `process.env.NODE_ENV` this way.

**Comment by mikekidder** [comment]
Closing as the solution will be separate configs for webpack.

Setting Node related environment variables via npm script tasks is brittle cross platform

**Comment by mrchief** [comment]
FWIW: https://www.npmjs.com/package/cross-env

**Comment by mlippens** [comment]
@mrchief, @mikekidder  confirmed that cross-env works well for me too.
